# Generated by Django 4.2.6 on 2023-10-25 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menu_unique_together'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_vote', models.IntegerField(default=0)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='restaurant.restaurant')),
            ],
        ),
    ]
